### ISSUE TITLE
Add phpunit.xml

### ISSUE THREAD

**Issue by bmitch** [Exadra37/package-skeleton#1]
Could add phpunit.xml within the package.

**Comment by Exadra37** [comment]
@bmitch the tests folder is already in the skeleton, but was already to late in the night to do anything more...

Ii will add it for sure and a lot of more cool stuff... we are just in the begin :)

Just keep an eye on it ;)

**Comment by bmitch** [comment]
@Exadra37 Sounds good. I'll try and put together a pull request for you...

**Comment by Exadra37** [comment]
@bmitch your contribute is welcome :+1:
