### ISSUE TITLE
Setup file in base

### ISSUE THREAD

**Issue by ghost** [Exadra37/package-skeleton#18]
Many projects have a set of commands that need to be run on initial setup `php artisan vendor:publish`, `php artisan migrate`, `php artisan seed` etc

Is there a best practice of where to put this other than the `README.md`? I was using a separate file (bash script) with these commands inside in the base of the `Nn4mTransition/framework`, run as executable to execute them in one command. 

Would it be an idea to standardize something like this (naming convention and placement) and reference it in the `README.md`? It would save a few copy and pastes on each new deploy (testing etc) and would be a step towards more automation in relation to the docker containers CI and automated testing.

**Comment by bmitch** [comment]
Having it in the `README.md` would be good and then maybe either a shell script or a "master" aritsan command that calls all the other commands could be handy as well.
